spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/weather?createDatabaseIfNotExist=true
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8081


app:
  scheduled:
    interval: 60000

weather-api: https://www.ilmateenistus.ee/ilma_andmed/xml/forecast.php?lang=eng